apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: webapp
        image: k8s4devs.azurecr.io/k8s4devs/webapp:v0.2
        imagePullPolicy: Always
        env:
        - name: K8S4DEVS_connectionstrings__redis
          value: redis
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name:  k8s4devs

---

apiVersion: v1
kind: Pod
metadata:
  name: redis
  labels:
    app: redis
spec:
  containers:
  - name: redis
    image: redis
    imagePullPolicy: Always
    ports:
    - containerPort: 6379
  imagePullSecrets:
    - name:  k8s4devs

---

apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  type: ClusterIP
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379

---

apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  type: NodePort
  selector:
    app: web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80