apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: web-app
  labels:
    name: k8s4devs-webapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: webapp
        image: k8s4devs.azurecr.io/k8s4devs/webapp:v0.2
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
      imagePullSecrets:
        - name:  k8s4devs